version: 2

jobs:
  build:
    docker:
      - image: circleci/node:8.11.4-stretch
    steps:
      - checkout
      - restore_cache:
          name: Restore Yarn Package Cache
          key: yarn-packages-{{ .Branch }}-{{ checksum "yarn.lock" }}
      - run:
          name: Install Dependencies, purely from the lockfile
          command: yarn install --frozen-lockfile
      - save_cache:
          name: Save Yarn Package Cache
          key: yarn-packages-{{ .Branch }}-{{ checksum "yarn.lock" }}
          paths:
            - node_modules/
      - run:
          name: Check Coding Style (standard)
          command: npm run lint
      - store_artifacts:
          path: /tmp/test-results
          prefix: tests
      - store_test_results:
          path: /tmp/test-results
