version: 2

jobs:
  build:
    docker:
      - image: circleci/node:12.14.0-buster
    steps:
      - checkout
      - restore_cache:
          name: Restore Yarn Package Cache
          keys: # Partial restoration if available: https://circleci.com/docs/2.0/caching/#yarn-node
            - yarn-packages-v1-{{ checksum "yarn.lock" }}
            - yarn-packages-v1-
      - run:
          name: Install Dependencies, purely from the lockfile
          command: yarn install --frozen-lockfile
      - save_cache:
          name: Save Yarn Package Cache
          key: yarn-packages-v1-{{ checksum "yarn.lock" }}
          paths:
            - node_modules/
      - run:
          name: Check Coding Style (standard)
          command: yarn lint
      - run:
          name: Run tests
          no_output_timeout: 1m
          command: |
            mkdir -p /tmp/test-results
            # Excluding non-xml lines (not starting with '<' or not indented)
            # using [:space:] rather than \s not parsed correctly by some versions of grep
            yarn test:ci | grep -Ei '^[[:space:]<]' > /tmp/test-results/test-results.xml
      - store_artifacts:
          path: /tmp/test-results
          prefix: tests
      - store_test_results:
          path: /tmp/test-results
